services:
  - type: web
    name: kalimat
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: "3000"
